### ISSUE TITLE
Singleton scope doesn't work

### ISSUE THREAD

**Issue by akkie** [ray-di/Ray.Di#13]
Hi,

I have the following binding defined:

``` php

<?php

$this->bind('com\mohiva\common\util\EventDispatcher')
   ->to('\com\mohiva\common\util\DefaultEventDispatcher')
   ->in(Scope::SINGLETON);
```

Now if I try to get the instance twice, I get two different objects.

``` php
<?php
$eventDispatcher = $injector->getInstance('com\mohiva\common\util\EventDispatcher');
var_dump(spl_object_hash($eventDispatcher));

$eventDispatcher = $injector->getInstance('com\mohiva\common\util\EventDispatcher');
var_dump(spl_object_hash($eventDispatcher));
```

Prints:

```
string(32) "00000000431a50c2000000002e406287"
string(32) "00000000431a50c4000000002e406287"
```

Cheers,
Christian

**Comment by koriym** [comment]
Thanks, @madapaja

**Comment by akkie** [comment]
Hi,

this bug isn't fixed. If I get the instances over the `Injector::getInstance()` method, then the method returns the same instances. But the automatically injected instances, with the help of the @Inject annotation, are not the same instances.

Cheers,
Christian

**Comment by madapaja** [comment]
I sent the pull request for this issue.

In `Injector::bindOneParameter()`, I found a bug that it can't read annotation information by `Config::fetch()`.
I guess this is because it call target class's config which is not enable to read Scope information. -  typehint(interface)  has binding(scope) information.

I've changed form `Config::fetch($typehint)` to `Config::fetch($target)` in `Injector::bindOneParameter()` to fix this issue.
All tests passed, although I'm not sure yet. So would you please confirm ?

Cheers.

---

自信が無いので日本語でも。。。
`Injector::bindOneParameter()` 内でアノテーションによるScope指定が読み取れない問題を見つけました。
これは、ターゲット（バインド先）クラスのconfigを呼んでいるため、Scope指定が読み取れないためだと思います。
（Scope指定は、Interface（タイプヒントされた）クラス内で行われているためです）

これを解決するために、`Config::fetch($target)` を `Config::fetch($typehint)` に変更しました。
テストは通りますが、これでいいのかどうか自信がないので、ご確認ください。

**Comment by koriym** [comment]
Thanks @madapaja  as always. The code seems OK. I will try with BEAR.Sunday app as well.

**Comment by koriym** [comment]
@akkie would you confirm it ?

**Comment by akkie** [comment]
Yes, it works. I think the issue can be closed.

**Comment by koriym** [comment]
Thank you all folks.
