### ISSUE TITLE
Avoid class_exists calls on explicit binding

### ISSUE THREAD

**Issue by akkie** [ray-di/Ray.Di#4]
Hi,

when I look through your code, I see several class_exists calls in the class AbstractModule. This forces all bindings to be loaded on definition time. I think this is bad, because if you have a huge list of bindings, then all classes will be loaded on definition time and not on binding time. So I think in most cases more classes will be load as actually needed.

What do you think?

Cheers,
Christian

**Comment by koriym** [comment]
Hi Christian,

This class_exists implementation was intentional, because 
1. Binding 'to' or 'toProvider' class name was given by explicit full path "string", I thought this can be sometime mistaken, maybe better to throw error in compile time more than in runtime.

This was original thought. However I thought again with your point out and I realized I never thought with "huge" list. Also, Maybe throwing error timing is not a big deal ? if so, lazy class loading is reasonable and better as you mentioned.
- Nice to hear from the first code review since I upload this library, Thank you ! I'm really excited :)

**Comment by akkie** [comment]
Hi koriym,

I work with Guice in Java and I like this concept of a DIC very well. And your lib is by far the best implementation of this concept I have found. Sure, a few small improvements here and there. But otherwise very solid.

So please do not thank me, I must thank you for your great work. (o;

Cheers,
Christian

**Comment by koriym** [comment]
As you might noticed in in Injector::getInstance(), I don't have enough experience with Guice. I choose it by its superior DIC implementation. The advice by someone who knows both are very helpful !
